insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Jilleen Parncutt', 'Zhongguan', 58, 436, 'Blue');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Benjamen Adran', 'Orleans', 16, 129, 'Maroon');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Ebenezer Tilling', 'Waoundé', 76, 540, 'Red');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Magdalena Coombe', 'San Bernardino', 21, 988, 'Fuscia');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Clementina Smallacombe', 'Struga', 44, 80, 'Orange');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Neill French', 'Buerarema', 67, 480, 'Goldenrod');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Georgeta Clerc', 'La Concepcion', 66, 296, 'Yellow');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Chic McGannon', 'Motygino', 77, 293, 'Green');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Ozzie Kauscher', 'Junglinster', 67, 216, 'Blue');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Vikki Mewett', 'Binglincha', 35, 914, 'Purple');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Harlen Zanetto', 'Kanggye-si', 43, 417, 'Green');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Nert Milne', 'Jinshan', 42, 835, 'Aquamarine');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Koressa Tallyn', 'Abu Dhabi', 72, 261, 'Aquamarine');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Emlyn Gisburne', 'Huqiu', 52, 346, 'Khaki');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Claudius MacLice', 'Skrzyszów', 79, 71, 'Blue');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Gare Tregian', 'Krzynowłoga Mała', 44, 995, 'Purple');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Ralina Hindes', 'Nggalak', 78, 117, 'Turquoise');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Lemmy Neat', 'Dolní Cerekev', 61, 580, 'Yellow');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Dierdre Whatman', 'Phôngsali', 37, 296, 'Mauv');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Alica MacKill', 'Thạnh Phú', 66, 537, 'Blue');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Granville Frodsam', 'Mingelchaur', 75, 985, 'Purple');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Layney Minards', 'Mafra', 55, 577, 'Mauv');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Fidel Lanphier', 'Xiaheqing', 59, 522, 'Indigo');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Cecelia Haycraft', 'Kalungu', 33, 214, 'Orange');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Georgianne Longlands', 'San Vicente', 74, 491, 'Turquoise');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Aeriell Brownstein', 'Concord', 66, 730, 'Fuscia');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Briana Varren', 'Dongcun', 52, 162, 'Violet');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Valera Bossom', 'Obrera', 33, 761, 'Purple');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Aloin Siman', 'Kinsale', 79, 785, 'Red');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Elsy Lamond', 'Kontiolahti', 60, 820, 'Fuscia');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Maighdiln Jindracek', 'Donggou', 66, 56, 'Khaki');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Roberto Kilgrew', 'Teuva', 20, 797, 'Turquoise');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Henderson Carik', 'Nishishinminato', 65, 457, 'Orange');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Fee Smullen', 'Castainço', 20, 416, 'Teal');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Alena Coupman', 'Xamtay', 46, 459, 'Green');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Micheil Antognelli', 'Shitang', 23, 289, 'Khaki');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Gerianne Sertin', 'Louisville', 37, 261, 'Orange');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Brandise D''orsay', 'Tangchijie', 44, 920, 'Violet');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Kesley Mazzilli', 'Karlobag', 33, 271, 'Turquoise');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Cally Wyllcocks', 'Ferme-Neuve', 62, 113, 'Pink');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Beckie Carmody', 'Montpellier', 68, 837, 'Blue');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Lyndsey Linfitt', 'Padilla', 22, 403, 'Turquoise');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Xerxes Zeal', 'Zhanghua', 46, 542, 'Puce');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Myrna Bradshaw', 'Jabinyānah', 39, 425, 'Aquamarine');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Carson Trevance', 'Zapala', 20, 961, 'Yellow');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Alexis Kendall', 'Wierzawice', 17, 987, 'Maroon');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Adey Ayscough', 'Piracuruca', 51, 201, 'Puce');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Woodrow Mullard', 'Cimongkor', 58, 817, 'Red');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Sheela Gepp', 'Łętownia', 10, 912, 'Turquoise');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Kathi Friel', 'Talmest', 55, 400, 'Pink');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Yancy Ralston', 'Gangba', 56, 71, 'Violet');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Christin Allkins', 'Longzhouwan', 70, 953, 'Violet');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Coreen Rosenberger', 'Timbrangan', 55, 359, 'Yellow');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Alexandro Devon', 'Katagum', 21, 106, 'Fuscia');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Leone Momford', 'Montpellier', 64, 354, 'Puce');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Kathie Buxsey', 'Masaya', 41, 141, 'Aquamarine');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Farlie Jovicic', 'Dolní Dunajovice', 26, 716, 'Khaki');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Parker Ganiclef', 'Xipingle', 65, 321, 'Maroon');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Horton MacRirie', 'Manga', 62, 584, 'Indigo');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Rasla Stubbert', 'Villeurbanne', 10, 404, 'Purple');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Laurel Kirley', 'Saint Paul', 40, 422, 'Teal');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Gloria Rudeforth', 'Kawengan', 39, 322, 'Puce');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Waldon De Micoli', 'Santo Domingo', 49, 731, 'Orange');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Carilyn Fernehough', 'Moss', 15, 689, 'Khaki');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Gaye Cawte', 'Beška', 64, 140, 'Orange');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Adena Pickrell', 'Paranapanema', 28, 657, 'Orange');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Fabe Mixworthy', 'Bi’r al Ḩufayy', 54, 948, 'Purple');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Humfrey Skerman', 'Malahide', 20, 717, 'Maroon');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Pietro Grayham', 'Zhaojia', 43, 671, 'Blue');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Hal Corkel', 'Aniso', 33, 539, 'Mauv');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Izaak Hambelton', 'Cetinje', 19, 797, 'Crimson');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Arabela Hendron', 'Ban Dan', 73, 699, 'Fuscia');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Doralia McCaskell', 'Cagliari', 57, 962, 'Teal');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Harv Hildrew', 'Baiyang', 16, 687, 'Purple');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Philis Nairns', 'Kertapura', 10, 529, 'Indigo');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Arleyne Fidilis', 'Ituzaingó', 59, 396, 'Red');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Kai Christopherson', 'Sława', 78, 130, 'Blue');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Brett Stones', 'Verkhov’ye', 57, 711, 'Crimson');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Lisbeth Gercke', 'Santarém', 78, 535, 'Purple');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Junina Brou', 'Vallentuna', 52, 706, 'Orange');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Ariela Diehn', 'Rancakole', 49, 964, 'Khaki');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Linet Boffin', 'Dashiren', 34, 966, 'Crimson');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Staford Jiggins', 'Liborina', 46, 898, 'Puce');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Christye Ernke', 'Iłowo -Osada', 29, 161, 'Fuscia');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Elene Beaty', 'Staré Hradiště', 66, 752, 'Maroon');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Cristiano Kirdsch', 'Wenbi', 57, 377, 'Crimson');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Sophey Bodill', 'Zhenchuan', 59, 777, 'Orange');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Frazer Bein', 'Stockholm', 15, 374, 'Goldenrod');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Lemmie Normanville', 'Grevená', 68, 246, 'Orange');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Zed O''Scanlan', 'Gunjur Kuta', 35, 682, 'Yellow');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Thia Petegrew', 'Granada', 54, 483, 'Turquoise');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Sayre Kearsley', 'Dawu', 36, 596, 'Red');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Melantha Southorn', 'Oelui', 74, 553, 'Puce');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Marlo Sussans', 'Ambulong', 57, 946, 'Fuscia');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Aurilia Yelden', 'Vale de São Cosme', 40, 128, 'Indigo');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Emelina Doole', 'Shuangpu', 36, 451, 'Pink');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Kerk Clemenza', 'Laxiong', 54, 604, 'Purple');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Sherm Guite', 'Likhobory', 75, 141, 'Goldenrod');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Em Borth', 'Bueng Kan', 58, 566, 'Yellow');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) VALUES ('Ebeneser Vina', 'Sumberpucung', 42, 428, 'Turquoise');
