insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Jilleen Parncutt', 'Zhongguan', 58, 436, 'Blue');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Benjamen Adran', 'Orleans', 16, 129, 'Maroon');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Ebenezer Tilling', 'Waoundé', 76, 540, 'Red');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Magdalena Coombe', 'San Bernardino', 21, 988, 'Fuscia');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Clementina Smallacombe', 'Struga', 44, 80, 'Orange');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Neill French', 'Buerarema', 67, 480, 'Goldenrod');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Georgeta Clerc', 'La Concepcion', 66, 296, 'Yellow');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Chic McGannon', 'Motygino', 77, 293, 'Green');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Ozzie Kauscher', 'Junglinster', 67, 216, 'Blue');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Vikki Mewett', 'Binglincha', 35, 914, 'Purple');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Harlen Zanetto', 'Kanggye-si', 43, 417, 'Green');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Nert Milne', 'Jinshan', 42, 835, 'Aquamarine');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Koressa Tallyn', 'Abu Dhabi', 72, 261, 'Aquamarine');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Emlyn Gisburne', 'Huqiu', 52, 346, 'Khaki');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Claudius MacLice', 'Skrzyszów', 79, 71, 'Blue');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Gare Tregian', 'Krzynowłoga Mała', 44, 995, 'Purple');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Ralina Hindes', 'Nggalak', 78, 117, 'Turquoise');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Lemmy Neat', 'Dolní Cerekev', 61, 580, 'Yellow');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Dierdre Whatman', 'Phôngsali', 37, 296, 'Mauv');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Alica MacKill', 'Thạnh Phú', 66, 537, 'Blue');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Granville Frodsam', 'Mingelchaur', 75, 985, 'Purple');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Layney Minards', 'Mafra', 55, 577, 'Mauv');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Fidel Lanphier', 'Xiaheqing', 59, 522, 'Indigo');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Cecelia Haycraft', 'Kalungu', 33, 214, 'Orange');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Georgianne Longlands', 'San Vicente', 74, 491, 'Turquoise');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Aeriell Brownstein', 'Concord', 66, 730, 'Fuscia');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Briana Varren', 'Dongcun', 52, 162, 'Violet');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Valera Bossom', 'Obrera', 33, 761, 'Purple');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Aloin Siman', 'Kinsale', 79, 785, 'Red');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Elsy Lamond', 'Kontiolahti', 60, 820, 'Fuscia');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Maighdiln Jindracek', 'Donggou', 66, 56, 'Khaki');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Roberto Kilgrew', 'Teuva', 20, 797, 'Turquoise');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Henderson Carik', 'Nishishinminato', 65, 457, 'Orange');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Fee Smullen', 'Castainço', 20, 416, 'Teal');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Alena Coupman', 'Xamtay', 46, 459, 'Green');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Micheil Antognelli', 'Shitang', 23, 289, 'Khaki');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Gerianne Sertin', 'Louisville', 37, 261, 'Orange');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Brandise D''orsay', 'Tangchijie', 44, 920, 'Violet');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Kesley Mazzilli', 'Karlobag', 33, 271, 'Turquoise');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Cally Wyllcocks', 'Ferme-Neuve', 62, 113, 'Pink');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Beckie Carmody', 'Montpellier', 68, 837, 'Blue');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Lyndsey Linfitt', 'Padilla', 22, 403, 'Turquoise');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Xerxes Zeal', 'Zhanghua', 46, 542, 'Puce');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Myrna Bradshaw', 'Jabinyānah', 39, 425, 'Aquamarine');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Carson Trevance', 'Zapala', 20, 961, 'Yellow');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Alexis Kendall', 'Wierzawice', 17, 987, 'Maroon');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Adey Ayscough', 'Piracuruca', 51, 201, 'Puce');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Woodrow Mullard', 'Cimongkor', 58, 817, 'Red');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Sheela Gepp', 'Łętownia', 10, 912, 'Turquoise');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Kathi Friel', 'Talmest', 55, 400, 'Pink');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Yancy Ralston', 'Gangba', 56, 71, 'Violet');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Christin Allkins', 'Longzhouwan', 70, 953, 'Violet');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Coreen Rosenberger', 'Timbrangan', 55, 359, 'Yellow');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Alexandro Devon', 'Katagum', 21, 106, 'Fuscia');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Leone Momford', 'Montpellier', 64, 354, 'Puce');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Kathie Buxsey', 'Masaya', 41, 141, 'Aquamarine');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Farlie Jovicic', 'Dolní Dunajovice', 26, 716, 'Khaki');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Parker Ganiclef', 'Xipingle', 65, 321, 'Maroon');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Horton MacRirie', 'Manga', 62, 584, 'Indigo');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Rasla Stubbert', 'Villeurbanne', 10, 404, 'Purple');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Laurel Kirley', 'Saint Paul', 40, 422, 'Teal');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Gloria Rudeforth', 'Kawengan', 39, 322, 'Puce');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Waldon De Micoli', 'Santo Domingo', 49, 731, 'Orange');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Carilyn Fernehough', 'Moss', 15, 689, 'Khaki');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Gaye Cawte', 'Beška', 64, 140, 'Orange');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Adena Pickrell', 'Paranapanema', 28, 657, 'Orange');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Fabe Mixworthy', 'Bi’r al Ḩufayy', 54, 948, 'Purple');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Humfrey Skerman', 'Malahide', 20, 717, 'Maroon');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Pietro Grayham', 'Zhaojia', 43, 671, 'Blue');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Hal Corkel', 'Aniso', 33, 539, 'Mauv');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Izaak Hambelton', 'Cetinje', 19, 797, 'Crimson');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Arabela Hendron', 'Ban Dan', 73, 699, 'Fuscia');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Doralia McCaskell', 'Cagliari', 57, 962, 'Teal');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Harv Hildrew', 'Baiyang', 16, 687, 'Purple');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Philis Nairns', 'Kertapura', 10, 529, 'Indigo');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Arleyne Fidilis', 'Ituzaingó', 59, 396, 'Red');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Kai Christopherson', 'Sława', 78, 130, 'Blue');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Brett Stones', 'Verkhov’ye', 57, 711, 'Crimson');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Lisbeth Gercke', 'Santarém', 78, 535, 'Purple');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Junina Brou', 'Vallentuna', 52, 706, 'Orange');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Ariela Diehn', 'Rancakole', 49, 964, 'Khaki');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Linet Boffin', 'Dashiren', 34, 966, 'Crimson');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Staford Jiggins', 'Liborina', 46, 898, 'Puce');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Christye Ernke', 'Iłowo -Osada', 29, 161, 'Fuscia');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Elene Beaty', 'Staré Hradiště', 66, 752, 'Maroon');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Cristiano Kirdsch', 'Wenbi', 57, 377, 'Crimson');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Sophey Bodill', 'Zhenchuan', 59, 777, 'Orange');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Frazer Bein', 'Stockholm', 15, 374, 'Goldenrod');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Lemmie Normanville', 'Grevená', 68, 246, 'Orange');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Zed O''Scanlan', 'Gunjur Kuta', 35, 682, 'Yellow');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Thia Petegrew', 'Granada', 54, 483, 'Turquoise');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Sayre Kearsley', 'Dawu', 36, 596, 'Red');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Melantha Southorn', 'Oelui', 74, 553, 'Puce');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Marlo Sussans', 'Ambulong', 57, 946, 'Fuscia');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Aurilia Yelden', 'Vale de São Cosme', 40, 128, 'Indigo');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Emelina Doole', 'Shuangpu', 36, 451, 'Pink');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Kerk Clemenza', 'Laxiong', 54, 604, 'Purple');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Sherm Guite', 'Likhobory', 75, 141, 'Goldenrod');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Em Borth', 'Bueng Kan', 58, 566, 'Yellow');
insert into MOCK_DATA (person_name, city, age, height_cm, favorite_color) values ('Ebeneser Vina', 'Sumberpucung', 42, 428, 'Turquoise');
